schemaVersion: 2.1.0
metadata:
  name: developer-images
components:
  - name: devtools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 4Gi
      memoryRequest: 512Mi
      cpuRequest: 500m
      cpuLimit: 3500m
